version: '3.1'

services:
  teamcity:
    image: jetbrains/teamcity-server:latest
    volumes:
      - teamcity-server-datadir:/data/teamcity-server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    user: root
    environment:
      - DOCKER_IN_DOCKER=start
      - SERVER_URL=http://192.168.1.5:8111
      - DOCKER_API_VERSION=1.39
    privileged: true
    volumes:
      - teamcity-agent-conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
  teamcity-agent-conf:
